// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrfnWucrCKTMYivm4_j4go1OgtLl9M_Ks',
    appId: '1:930423513347:android:1fa9ad2179c424f6f3c936',
    messagingSenderId: '930423513347',
    projectId: 'tindatrack-73678',
    storageBucket: 'tindatrack-73678.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqpPMYuY33KieLJ1uXRM3ptRPQ6MuzS6Q',
    appId: '1:930423513347:ios:4354ea961362e709f3c936',
    messagingSenderId: '930423513347',
    projectId: 'tindatrack-73678',
    storageBucket: 'tindatrack-73678.firebasestorage.app',
    androidClientId: '930423513347-hf86t5dl6ctij4k0v6osekcvr36p9a7u.apps.googleusercontent.com',
    iosClientId: '930423513347-tlp8am9b0rebnemne1so9se7lhlp1unn.apps.googleusercontent.com',
    iosBundleId: 'com.tindatrack.tindaTrack',
  );
}
